#!/bin/bash

# Copyright (C) 2012 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# Distributed under the ISC license which can be found in the LICENSE file.

# Before you run the mount script, run this to create
# the folders for the mountpoints to mount to

# Import functions
source resources/variables.sh
source resources/functions_generic.sh

# Check to see if a drive was given
if [[ -z "${1}" ]]; then
	werr "A root wasn't passed to this script, exiting"
fi

wecho "Creating default directories"

mount ${1} ${PREFIX}

for x in ${DEFAULT_DIRS}; do
	mkdir -p ${PREFIX}/${x}
done

umount ${PREFIX}
