#!/bin/bash

# Copyright (C) 2012-2018 Jonathan Vasquez <jon@xyinn.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see<https://www.gnu.org/licenses/>.

Drive="$1"
ChrootDir="$2"

# Check to see if a drive was given
if [[ -z "${Drive}" ]] || [[ -z "${ChrootDir}" ]]; then
    echo "Usage: extlinux-install <drive> <target dir>"
    exit 1
fi

# Install extlinux bootloader
echo "Installing extlinux bootloader ..."

# Bootloader Directory
LoaderDir="${ChrootDir}/boot/extlinux"

if [[ -d "${LoaderDir}" ]]; then
    chattr -i "${LoaderDir}"/ldlinux.sys
    rm -rf "${LoaderDir}"
fi

mkdir -p "${LoaderDir}"

# Install bootloader and copy config and menu file
extlinux --install "${LoaderDir}"

cp -f examples/bootloader/extlinux.conf "${LoaderDir}"
cp -f /usr/share/syslinux/{libutil,menu}.c32 "${LoaderDir}"

# Set BIOS Legacy Flag
sgdisk "${Drive}" --attributes=1:set:2

# Flash GPT/MBR file to drive
dd if=/usr/share/syslinux/gptmbr.bin of="${Drive}"
