#!/bin/bash

# Copyright (C) 2012-2019 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Drive="$1"
ChrootDir="$2"

# Check to see if a drive was given
if [[ -z "${Drive}" ]] || [[ -z "${ChrootDir}" ]]; then
    echo "Usage: extlinux-install <drive> <target dir>"
    exit 1
fi

# Install extlinux bootloader
echo "Installing extlinux bootloader ..."

# Bootloader Directory
LoaderDir="${ChrootDir}/boot/extlinux"

if [[ -d "${LoaderDir}" ]]; then
    chattr -i "${LoaderDir}"/ldlinux.sys
    rm -rf "${LoaderDir}"
fi

mkdir -p "${LoaderDir}"

# Install bootloader and copy config and menu file
extlinux --install "${LoaderDir}"

cp -f examples/bootloader/extlinux.conf "${LoaderDir}"
cp -f /usr/share/syslinux/{libutil,menu}.c32 "${LoaderDir}"

# Set BIOS Legacy Flag
sgdisk "${Drive}" --attributes=1:set:2

# Flash GPT/MBR file to drive
dd if=/usr/share/syslinux/gptmbr.bin of="${Drive}"
