#!/bin/bash

# Copyright (C) 2012-2019 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_ChrootDir="$1"

if [[ -z "${_ChrootDir}" ]]; then
    echo "You must pass the directory you want to chroot into."
    exit 1
fi

mount --rbind /proc "${_ChrootDir}"/proc
mount --rbind /dev "${_ChrootDir}"/dev
mount --rbind /sys "${_ChrootDir}"/sys

# Copy over network config
_ResolvConfig="/etc/resolv.conf"

if [[ ! -f "${_ResolvConfig}" ]]; then
    cp -f "${_ResolvConfig}" "${_ChrootDir}"/etc
fi

# Copy over zpool.cache (if exists)
_ZpoolCachePath="/etc/zfs/zpool.cache"

if [[ -f "${_ZpoolCachePath}" ]]; then
    _ZpoolCacheChrootPath="${_ChrootDir}${_ZpoolCachePath}"

    if [[ ! -d "${_ZpoolCacheChrootPath}" ]]; then
        mkdir -p "$(dirname ${_ZpoolCacheChrootPath})"
    fi

    cp -f "${_ZpoolCachePath}" "${_ZpoolCacheChrootPath}"
fi

echo "Chrooting ..."
env -i HOME=/root TERM="${TERM}" chroot "${_ChrootDir}" /bin/bash --login

echo "Unchrooting ..."
umount -l "${_ChrootDir}"/{proc,dev,sys}
