#!/bin/bash

# Copyright (C) 2012 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# Distributed under the ISC license which can be found in the LICENSE file.

# Import functions
source resources/variables.sh
source resources/functions_generic.sh

# Check to see if a choice was passed
if [[ ! -z "${1}" ]]; then
	case ${1} in
	1|2|3|4|5|6|7) 
		choice=${1}
		;;
	*)
		print_options
		err "Invalid choice, must be between 1-7. Exiting."
		;;
	esac
fi

# Print header
print_header

# Get the flavor you want
menu_stage

# Let the games begin
wecho "Checking to see if you have ${STAGE}"

# Download Stage 3 and Portage
if [[ ! -f "${FILESDIR}/${STAGE}" ]]; then
	wecho "Downloading ${STAGE}"
	wget -P ${FILESDIR} ${FLAVOR}
else
	wecho "You already have ${STAGE} :)."
fi

wecho "Checking to see if you have ${PORTAGE}"
if [[ ! -f "${FILESDIR}/${PORTAGE}" ]]; then
	wecho "Downloading ${PORTAGE}"
	wget -P ${FILESDIR} ${PFLAVOR}
else
	wecho "You already have ${PORTAGE} :)."
fi

# Extract Stage3 and Portage
wecho "Extracting ${STAGE}"
tar -xpf ${FILESDIR}/${STAGE} -C ${PREFIX}
wecho "Extracting ${PORTAGE}"
tar -xf ${FILESDIR}/${PORTAGE} -C ${PREFIX}/usr

# Decides and prints messages for specific flavor set in MESSAGE

if [[ "${MESSAGE}" == "Gentoo" ]]; then
	wecho "Congratulations on your new ${MESSAGE} setup!"
elif [[ "${MESSAGE}" == "Funtoo" ]]; then
	wecho "Congratulations on your new ${MESSAGE} setup!"
	wecho "After you chroot, go into the /usr/portage directory and set 
	       your branch to point to funtoo.org. Issue a 'git checkout funtoo.org'."
else
	wecho "Error detecting what messages to display.. skipping"
fi

wecho "If you want to make an initramfs, you can clone my initramfs creator by 
       typing 'git clone git://github.com/fearedbliss/Bliss-Initramfs-Creator.git"

wecho "Installation Complete!"
