#!/bin/bash

# Copyright (C) 2012 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# Distributed under the ISC license which can be found in the LICENSE file.

# Import functions
source resources/variables.sh
source resources/functions_generic.sh

wecho "Unmounting Filesystems"

VG_NAME="vg"

MOUNTPOINTS="
proc
dev
sys
/dev/sda1
/dev/${VG_NAME}/home
/dev/${VG_NAME}/var
/dev/${VG_NAME}/src
/dev/${VG_NAME}/portage
/dev/${VG_NAME}/root
"

for x in ${MOUNTPOINTS}; do
        if [[ "${x}" == "proc" ]] ||
           [[ "${x}" == "dev" ]]  ||
           [[ "${x}" == "sys" ]]; then
                umount ${PREFIX}/${x}
        else
                umount ${x}
        fi
done

# Turn off swap
swapoff /dev/vg/swap
